# Geometry Analysis Homework Solution

In [95]:
import numpy
import os

In [96]:
file_name=os.path.join('water.xyz')
coord_file=numpy.genfromtxt(fname=file_name, skip_header=2,  dtype='unicode')
print(coord_file)

[['O' '0.000000' '-0.007156' '0.965491']
 ['H1' '-0.000000' '0.001486' '-0.003471']
 ['H2' '0.000000' '0.931026' '1.207929']]


In [97]:
atom_type=coord_file[:,0]
print(atom_type)
coordinates=(coord_file[:,1:]).astype(numpy.float)
print(coordinates)

['O' 'H1' 'H2']
[[ 0.       -0.007156  0.965491]
 [-0.        0.001486 -0.003471]
 [ 0.        0.931026  1.207929]]


In [98]:
coord_dict={}
num_atoms=len(atom_type)
for i in range(0,len(atom_type)):
    coord_dict[atom_type[i]]=coordinates[i]
print(coord_dict)

{'O': array([ 0.      , -0.007156,  0.965491]), 'H1': array([-0.      ,  0.001486, -0.003471]), 'H2': array([0.      , 0.931026, 1.207929])}


$$ distance = \sqrt((x1-x2)^2+(y1-y2)^2+(z1-zq)^2) $$

In [99]:
for key in coord_dict.items():
    print(key)

('O', array([ 0.      , -0.007156,  0.965491]))
('H1', array([-0.      ,  0.001486, -0.003471]))
('H2', array([0.      , 0.931026, 1.207929]))


In [100]:
num_atoms=len(atom_type)
for num1 in range(0,num_atoms):
    for num2 in range(0,num_atoms):
        if num1<num2:
            x_distance=coordinates[num1,0]-coordinates[num2,0]
            y_distance=coordinates[num1,1]-coordinates[num2,1]
            z_distance=coordinates[num1,2]-coordinates[num2,2]
            distance_12=numpy.sqrt(x_distance**2+y_distance**2+z_distance**2)
            if (distance_12<1.5):
                print(F'{atom_type[num1]} to {atom_type[num2]}:{distance_12}')

O to H1:0.9690005374652793
O to H2:0.9690003348647513
